# main title
title: Prof. Ricardo Miranda Martins

# protocol & hostname for your site (it does not end with a '/')
url: https://rmiranda99.github.io

author:
  name: Ricardo Miranda Martins

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
